apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - metadata-writer
  - cluster-scoped
resources:
  - ml-pipeline-apiserver-deployment.yaml
  - ml-pipeline-apiserver-role.yaml
  - ml-pipeline-apiserver-rolebinding.yaml
  - ml-pipeline-apiserver-sa.yaml
  - ml-pipeline-apiserver-service.yaml
  - ml-pipeline-persistenceagent-deployment.yaml
  - ml-pipeline-persistenceagent-role.yaml
  - ml-pipeline-persistenceagent-rolebinding.yaml
  - ml-pipeline-persistenceagent-sa.yaml
  - ml-pipeline-scheduledworkflow-deployment.yaml
  - ml-pipeline-scheduledworkflow-role.yaml
  - ml-pipeline-scheduledworkflow-rolebinding.yaml
  - ml-pipeline-scheduledworkflow-sa.yaml
  - ml-pipeline-ui-deployment.yaml
  - ml-pipeline-ui-configmap.yaml
  - ml-pipeline-ui-role.yaml
  - ml-pipeline-ui-rolebinding.yaml
  - ml-pipeline-ui-sa.yaml
  - ml-pipeline-ui-service.yaml
  - ml-pipeline-viewer-crd-role.yaml
  - ml-pipeline-viewer-crd-rolebinding.yaml
  - ml-pipeline-viewer-crd-deployment.yaml
  - ml-pipeline-viewer-crd-sa.yaml
  - ml-pipeline-visualization-deployment.yaml
  - ml-pipeline-visualization-sa.yaml
  - ml-pipeline-visualization-service.yaml
  - pipeline-runner-role.yaml
  - pipeline-runner-rolebinding.yaml
  - pipeline-runner-sa.yaml
  - container-builder-sa.yaml
  - viewer-sa.yaml
  - kfp-pipeline-config.yaml
  - kfp-launcher-configmap.yaml
patchesStrategicMerge:
  - apiserver-deployment.yaml
  - metadata-writer-deployment.yaml
images:
  - name: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/api-server
    newName: docker.io/aipipeline/api-server
    newTag: 1.0.0
  - name: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/persistenceagent
    newName: docker.io/aipipeline/persistenceagent
    newTag: 1.0.0
  - name: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/scheduledworkflow
    newName: docker.io/aipipeline/scheduledworkflow
    newTag: 1.0.0
  - name: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/frontend
    newName: docker.io/aipipeline/frontend
    newTag: 1.0.0
  - name: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/viewer-crd-controller
    newTag: 1.7.0
  - name: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/visualization-server
    newTag: 1.7.0
  - name: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/metadata-writer
    newName: docker.io/aipipeline/metadata-writer
    newTag: 1.0.0
